name: smartexit_app
description: "SmartExit - Scan. Pay. Exit."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  shimmer: ^3.0.0

  # Animations
  flutter_animate: ^4.3.0

  # Networking
  http: ^1.2.0

  # State Management
  flutter_riverpod: ^2.4.9

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Socket.io for realtime
  socket_io_client: ^2.0.3+1

  # QR generation
  qr_flutter: ^4.1.0
  pretty_qr_code: ^3.3.0
  flutter_svg: ^2.0.10

  # QR Scanning
  mobile_scanner: ^7.1.4

  # Charts (Admin)
  fl_chart: ^0.66.0

  # Auth / Security
  jwt_decoder: ^2.0.1

  # Payment
  razorpay_flutter: ^1.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo/smartexit_logo.png
